/** Write docs/API/openapi.json and docs/API.md from the live OpenAPI registry. */
import fs from 'node:fs';
import path from 'node:path';
import { createApp } from '../src/app';
import { buildOpenApiDocument } from '../src/openapi';

createApp(); // registers every route's documentation
const doc = buildOpenApiDocument() as unknown as {
  paths: Record<
    string,
    Record<string, { summary?: string; tags?: string[]; security?: unknown[] }>
  >;
};
const root = path.resolve(__dirname, '../../../docs');
fs.mkdirSync(path.join(root, 'API'), { recursive: true });
fs.writeFileSync(path.join(root, 'API', 'openapi.json'), JSON.stringify(doc, null, 2) + '\n');

const rows: string[] = [];
const byTag = new Map<string, string[]>();
for (const [p, ops] of Object.entries(doc.paths)) {
  for (const [method, op] of Object.entries(ops)) {
    const tag = op.tags?.[0] ?? 'Other';
    const auth = p.startsWith('/admin') ? 'admin' : op.security ? 'user' : 'public';
    byTag.set(tag, [
      ...(byTag.get(tag) ?? []),
      `| \`${method.toUpperCase()}\` | \`${p}\` | ${auth} | ${op.summary ?? ''} |`,
    ]);
  }
}
for (const [tag, lines] of byTag)
  rows.push(
    `\n### ${tag}\n\n| Method | Path | Access | Summary |\n|---|---|---|---|\n${lines.join('\n')}`,
  );

const md = `# BioMed Zones API

> Generated by \`npm run openapi:export -w @biomed/api\` from the OpenAPI registry. The interactive
> reference is served at **/api/docs** (Swagger UI) and the machine-readable document at
> **/api/openapi.json**; a copy is committed in [API/openapi.json](API/openapi.json).

Base URL through the gateway: \`http://localhost:8080/api\`.

## Authentication

- \`POST /auth/login\` sets two httpOnly, SameSite=Strict cookies: \`bz_access\` (JWT, 15 min) and
  \`bz_refresh\` (opaque token, 7 days). API clients may send the access token as \`Authorization: Bearer\`.
- \`POST /auth/refresh\` rotates the refresh token; reusing an already-rotated token revokes the whole
  session family (theft detection). Refresh tokens are stored as SHA-256 hashes only.
- Passwords: Argon2id (m = 19 MiB, t = 2, p = 1), 12–128 characters.
- Roles: \`CONTRIBUTOR\` (default on registration) and \`ADMIN\`.
- State-changing requests from browsers must carry a whitelisted \`Origin\` (CORS_ORIGINS).
- Rate limits: 1,500 requests / 15 min per IP overall, 20 / 15 min on authentication, 120 / h on
  contribution writes and reference checks, 20 / min on PDF reports (HTTP 429 with RateLimit headers).

Demo accounts (seeded): \`admin@biomed-zones.local\` / \`BioMedAdmin!2026\` and
\`contributor@biomed-zones.local\` / \`BioMedContrib!2026\`.

## Errors

All errors are JSON: \`{ "error": "<code>", "message": "...", "details": [...] }\`. Validation errors
(400, code \`validation_error\`) list every invalid field as \`{ path, message }\`.

## Endpoints
${rows.join('\n')}
`;
fs.writeFileSync(path.join(root, 'API.md'), md);
console.log(`wrote ${Object.keys(doc.paths).length} paths`);
